name: Build and test

on:
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test
      - name: Validate
        run: |
          pnpm run lint
          pnpm run check-format
      - name: Build
        run: pnpm run build
