name: Release

on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Release to npm
        id: release
        # run only on upstream repo (not forks) and
        # only if commit message does not contain [ci skip] or [skip ci]
        if: |
          github.repository == 'single-spa/single-spa-react' &&
          !(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release
      - name: Generate changelog
        uses: actions/github-script@v6
        # if: steps.release.outcome == 'success' # only if release step ran successfully
        with:
          script: |
            const pkgJson = require('./package.json')
            const branchName = `update-changelog-for-${pkgJson.version}`
            const message = `Update changelog for ${pkgJson.version} [skip ci]`
            try {
              await exec.exec('git', ['checkout', '-b', branchName])
              await exec.exec('pnpm', ['run', 'changelog']);
              await exec.exec('git', ['add', 'CHANGELOG.md']); 
              await exec.exec('git', ['commit', '-m', message]); 
              github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: branchName,
                base: 'main'
              })
            } catch(e) {
              console.info('Error creating changelog PR. Run `pnpm run changelog` manually and create a PR if necessary.')
              console.error(e)
            }
